### ISSUE TITLE
Move printMessage function parameter to a --debug flag or environment variable

### ISSUE THREAD

**Issue by Tebro** [mjalas/messaging-client#8]
Currently some functions in the MessagingClient class take a "printMessage" parameter. This would be better as a global setting configured either via a runtime flag or environment variable. 

To further improve different log levels could be implemented.

**Comment by mjalas** [comment]
Adding a 'debug' mode should fix that, and different levels could also be a good thing to think about. However, the levels at this point would be to over engineer it.

**Comment by mjalas** [comment]
Added a debug command line option, to fix the issue.
